# Build app stage
FROM node:18-slim AS build
WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 5173

# Run app stage
FROM node:18-slim
WORKDIR /app

COPY --from=build /app/dist /dist
COPY --from=build /app/node_modules /node_modules
COPY --from=build /app/package*.json .

EXPOSE 5173

ENTRYPOINT [ "npm", "run", "preview" ]