services:
  backend:
    image: backend
    container_name: backend
    build:
      context: /backend
      dockerfile: dockerfile
    ports:
      - 8080:8080
    env_file:
      - /backend/.env

  frontend:
    depends_on:
      - backend
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    env_file:
      - /frontend/.env
