services:
  # backend:
  #   build:
  #     context: /backend
  #   ports:
  #     - 8081:8081
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
