jobs:
  - job: build_app
    displayName: Build application
    steps:
      - task: NodeTool@0
        displayName: "Install Node 18"
        inputs:
          versionSpec: "18.x"

      - script: npm run build
        displayName: Run build

  - job: publish_artifact
    displayName: Publish artifact
    dependsOn: build_app
    steps:
      - task: PublishBuildArtifact@1
        displayName: Copy build result to Artifact Staging directory
        inputs:
          PathToPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: drop
