parameters:
  - name: frontendFolderDirectory
    type: string

jobs:
  - job: build_app
    displayName: Build application
    steps:
      - task: NodeTool@0
        displayName: "Install Node 18"
        inputs:
          versionSpec: "18.x"

      - script: |
          echo "Working directory"
          echo "$(System.DefaultWorkingDirectory)"
          echo "${{ parameters.frontendFolderDirectory }}"
          echo "$(pwd)"

      - script: npm run build
        displayName: Run build
        workingDirectory: "frontend"

  - job: publish_artifact
    displayName: Publish artifact
    dependsOn: build_app
    steps:
      - task: PublishBuildArtifacts@1
        displayName: Copy build result to Artifact Staging directory
        inputs:
          PathToPublish: "${{ parameters.frontendFolderDirectory }}/dist"
          ArtifactName: drop
