# Main frontend template
trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - pipelines/frontend
      - frontend
pool:
  name: "self-agent-pool"

stages:
  - stage: build
    displayName: Build application
    jobs:
      - template: ./build-job-template.yml
        parameters:
          frontendFolderDirectory: $(frontendFolderDirectory)
  # - stage: deploy
  #   displayName: Deploy to Azure
  #   jobs:
  #     - template: ./deploy-job-template.yml
