# Main frontend template
trigger:
  - dev

pool:
  name: "self-agent-pool"

stages:
  - stage: build
    displayName: Build application
    jobs:
      - template: ./build-job-template.yml
  # - stage: deploy
  #   displayName: Deploy to Azure
  #   jobs:
  #     - template: ./deploy-job-template.yml
