
# Build app stage
FROM gradle:7.5.1-jdk17 AS build
WORKDIR /home/gradle/app
COPY . .
RUN ./gradlew build --no-daemon

# Run app stage
FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /home/gradle/app/build/libs/* app.jar
EXPOSE 8000

ENTRYPOINT [ "java", "-jar" , "app.jar" ] 