# Frontend ViteJS + React template
trigger:
  - dev

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ./frontend-build-job-template.yml
      - template: ./frontend-deploy-job-template.yml
