logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 8080

database:
  uri: ${MONGO_DB_CONNECTION_STRING}

azure:
  keyvault:
    enabled: true
    uri: ${AZURE_KEYVAULT_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
